apiVersion: tekton.dev/v1alpha1
kind: Run
metadata:
  name: my-embedded-run
spec:
  spec:
    apiVersion: custom.tekton.dev/v1alpha1
    kind: TaskGroup
    spec:
      steps:
      - name: clone
        uses:
          taskRef:
            name: my-git-clone
      - name: build
        image: docker.io/library/golang:latest
        script: |
          ls -l /workspace; ls -l /workspace/foo; true
          cd /workspace/foo && go build -v ./...
